### PR TITLE
API

### LINKED ISSUE #4: Design API for recovering data from Google Earth Engine
Design and implement a simple API for taking the input selections from the UI (input geometries of MSA's or metropolitan service areas, and date ranges for the analysis, e.g. start and end dates) and returning the output (time series of mean NO2 concentrations over these geometries) as a pandas dataframe.

The design will closely follow the version in [this colab cell](https://colab.research.google.com/drive/1lynJQIThuq98t8SZOvw09C6c8lF2-msd#scrollTo=VAzcOj5vMb0P&line=5&uniqifier=1)

To avoid being blocked by the generation of the geometries for MSA's initially just use the geometry of the level 3 admin boundary as provided by the 'FAO/GAUL_SIMPLIFIED_500m/2015/level2' dataset in google earth engine.

After implementing this simple API, you should first create an design document addressing the following issues

- what is the requirement of this API (function call and return signatures, and how these fit into the overall application design)
- What is the format of the  inputs and outputs for any server side processing
- What are the latency requirements of executing this API  in view of the UI responsiveness
- Would any preprocessing be beneficial for reducing application latency.
- What is the memory requirement on the client for storing the output tables

### LINKED ISSUE #28: Integrate API into Dash app
Have the Dash app send requests to the API in order to retrieve data in real time, instead of using an existing csv.

### PR DESCRIPTION
**Pull request by APoulad**
This API takes polygon geometries as an input to filter the NO2 data. It does not use any other definitions for areas other than what you provide it. The API also has a few fixes over the previous iteration, removing some code that was dormant.

There is still a problem to be addressed: It can only take one geometry at a time. This will hopefully be fixed at a later point.

### CODE REVIEW

**Comment by EStein-Projects** [comment]
Can you move the Demo file to the Demos folder?

**Comment by rameshnatarajanus** [comment]
the code for the API seems to be in several different places, a couple of notebooks in this branch and another version in a notebook in another branch. 

I am going to approve this version to get a move on, but i think the getConc function given here will not work for images without bands, as the call to reduceregions will fail.

**Review by rameshnatarajanus — APPROVED** [review]
Same code in 2 different places for the api access.  I understand the need for it here, but  this will eventually need refactoring.  Also not sure about the correctness of getConc method for images without bands.

**Comment by rameshnatarajanus** [comment]
Is this branch active? I see the same code in another branch which seems to have fixed some of the issues with the api arguments sdate, edate in this branch.   If not needed this branch/issue can be closed.

**Comment by APoulad** [comment]
> the code for the API seems to be in several different places, a couple of notebooks in this branch and another version in a notebook in another branch.

This branch has the code twice, once for the API alone, and once with a demonstration of calling it.

There is only one other branch with the API, but that one still uses the FAO GAUL Global Administrative Unit Layers, instead of being able to input geometries.

**Pull request merged**
