### PR TITLE
Es 19 MSA population update

### LINKED ISSUE #19: Add Population Metadata to CBSA API

### PR DESCRIPTION
**Pull request by EStein-Projects**
Just population so far

### CODE REVIEW

**Comment by rameshnatarajanus** [comment]
Elchonon, thanks this looks very nice and the api is clean.  A few questions:

- Why are there 2 notebooks MSA_class and MSA_populations?  are they identical  or almost identical and if so can you dedup them?
- How is this api being used by the client?  Do you need to move this MSA class to a .py file which can be imported?
- Neither of the files contains an example of the use of the API
- the noun "areas" is a bit overloaded in your class. I assume it is not really the actual area in sq km but just an abbreviation for "metropolitan service area"?  If so, might make sense to just use "msa" as the noun here.

**Comment by EStein-Projects** [comment]
> * Why are there 2 notebooks MSA_class and MSA_populations? Are they identical or almost identical and if so can you dedup them?
- MSA_class is the useful one. MSA_populations was a deprecated demo and has been deleted.
> * How is this api being used by the client?  Do you need to move this MSA class to a .py file which can be imported?
- Right now it is being used by importing it with the import-ipynb module. I have now also uploaded a version in .py format.
> * Neither of the files contains an example of the use of the API
- I have clarified the demo. The .ipynb version of the class, located in the "Demos" folder, contains the demo.
> * the noun "areas" is a bit overloaded in your class. I assume it is not really the actual area in sq km but just an abbreviation for "metropolitan service area"?  If so, might make sense to just use "msa" as the noun here.
- Good point. The functions and properties now all use "msas" in place of "areas."

**Comment by rameshnatarajanus** [comment]
@RimazeiHamachshav thanks for the nice work.  Quite interesting to learn from this issue that you can import functions defined inside notebooks!

**Review by rameshnatarajanus — APPROVED** [review]
Approved. Please go ahead and merge

**Comment by EStein-Projects** [comment]
> @RimazeiHamachshav thanks for the nice work. Quite interesting to learn from this issue that you can import functions defined inside notebooks!

Thanks. To give credit where credit is due though, I believe the import-ipynb module was Aaron's discovery.

**Pull request merged**
