### PR TITLE
Forecaster v1.0

### LINKED ISSUE #33: Create forecasting models
Initial version of forecasting models specification, training and forecasting (included structural decomposition) in the dailydata.ipynb notebook. Needs to be adapted to the NOx data from our app.

ES edit -  Completed with .py version of the forecaster

### PR DESCRIPTION
**Pull request by EStein-Projects**

### CODE REVIEW

**Comment by APoulad** [comment]
please move the forecaster.py file into a folder

**Comment by EStein-Projects** [comment]
> please move the forecaster.py file into a folder

I would just like to focus this PR on merging in the code. If you would like to reorganize everything we can do that in a separate PR.

**Review by APoulad — APPROVED** [review]

**Comment by rameshnatarajanus** [comment]
@RimazeiHamachshav this looks like a very clean interface.   Nice work.  I am approving and you can go ahead and merge. 

@APoulad, @Ori I just noticed the code for getting the timeseries - this code will not have repeated dates because it computes a dailymediancomposite which is excellent to note.

**Review by rameshnatarajanus — APPROVED** [review]
Nice work.

**Pull request merged**
